import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homelistsystemmanager">HomeListSystemManager</Link>
        </li>
        <li>
          <Link to="/organizationedit">OrganizationEdit</Link>
        </li>
        <li>
          <Link to="/homenormaluser">HomeNormalUser</Link>
        </li>
        <li>
          <Link to="/homesystemmanager">HomeSystemManager</Link>
        </li>
        <li>
          <Link to="/organizationmanagement">OrganizationManagement</Link>
        </li>
        <li>
          <Link to="/friendsremoveselect">FriendsRemoveSelect</Link>
        </li>
        <li>
          <Link to="/homelistnormaluser">HomeListNormalUser</Link>
        </li>
        <li>
          <Link to="/accountmanagement">AccountManagement</Link>
        </li>
        <li>
          <Link to="/organizationdetail">OrganizationDetail</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/announcedetail">AnnounceDetail</Link>
        </li>
        <li>
          <Link to="/sendannounce">SendAnnounce</Link>
        </li>
        <li>
          <Link to="/userreportsselect">UserReportsSelect</Link>
        </li>
        <li>
          <Link to="/">LogIn</Link>
        </li>
        <li>
          <Link to="/announceboard">AnnounceBoard</Link>
        </li>
        <li>
          <Link to="/userremoveselect">UserRemoveSelect</Link>
        </li>
        <li>
          <Link to="/friends">Friends</Link>
        </li>
        <li>
          <Link to="/homelistvistor">HomeListVistor</Link>
        </li>
        <li>
          <Link to="/generalactivitiesform">GeneralActivitiesForm</Link>
        </li>
        <li>
          <Link to="/store">Store</Link>
        </li>
        <li>
          <Link to="/locationmap">LocationMap</Link>
        </li>
        <li>
          <Link to="/homevistor">HomeVistor</Link>
        </li>
        <li>
          <Link to="/activitiespublishselect">ActivitiesPublishSelect</Link>
        </li>
        <li>
          <Link to="/tracepublishercollection">TracePublisherCollection</Link>
        </li>
        <li>
          <Link to="/reportform">ReportForm</Link>
        </li>
        <li>
          <Link to="/emergencyactivitiesform">EmergencyActivitiesForm</Link>
        </li>
        <li>
          <Link to="/editorganizationinterview">EditOrganizationInterview</Link>
        </li>
        <li>
          <Link to="/activitydetail">ActivityDetail</Link>
        </li>
        <li>
          <Link to="/userrestrictselect">UserRestrictSelect</Link>
        </li>
        <li>
          <Link to="/organizationpoweredit">OrganizationPowerEdit</Link>
        </li>
        <li>
          <Link to="/modifyforgetpassword">ModifyForgetPassword</Link>
        </li>
        <li>
          <Link to="/activitiesrecords">ActivitiesRecords</Link>
        </li>
        <li>
          <Link to="/modifypassword">ModifyPassword</Link>
        </li>
        <li>
          <Link to="/messageboard">MessageBoard</Link>
        </li>
        <li>
          <Link to="/supervise">Supervise</Link>
        </li>
        <li>
          <Link to="/activitiesmodify">ActivitiesModify</Link>
        </li>
        <li>
          <Link to="/activitiesmanagement">ActivitiesManagement</Link>
        </li>
        <li>
          <Link to="/organizationcreate">OrganizationCreate</Link>
        </li>
        <li>
          <Link to="/propsmanager">PropsManager</Link>
        </li>
        <li>
          <Link to="/activitiescollection">ActivitiesCollection</Link>
        </li>
        <li>
          <Link to="/judgementsuccessnotice">JudgementSuccessNotice</Link>
        </li>
        <li>
          <Link to="/activitydetailvistor">ActivityDetailVistor</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
